import { MockedResponse } from "@apollo/client/testing";
import { FetchExpensesDocument, FetchExpensesQuery } from "./generated/graphql";

type Expense = {
  amount: number;
  category: string;
  date: string;
  id: number;
  transaction: string;
};

const expenses: Expense[] = [
  {
    amount: 24.63,
    category: "Family",
    date: "1/20/21",
    id: 1,
    transaction: "Amazon.com*CH81I4OM3",
  },
  {
    amount: 203.73,
    category: "Restaurants",
    date: "1/20/21",
    id: 2,
    transaction: "TOCK ATMANRESA",
  },
  {
    amount: 573.13,
    category: "Utilities",
    date: "1/19/21",
    id: 3,
    transaction: "SAN JOSE UTILITIES",
  },
  {
    amount: 115.79,
    category: "Gadgets",
    date: "1/18/21",
    id: 4,
    transaction: "Amazon.com*T22ZL3LV3",
  },
  {
    amount: 17.99,
    category: "Entertainment",
    date: "1/18/21",
    id: 5,
    transaction: "PAYPAL *NETFLIX.COM",
  },
  {
    amount: 23.48,
    category: "Restaurants",
    date: "1/17/21",
    id: 6,
    transaction: "UBER   EATS",
  },
  {
    amount: 24.73,
    category: "Shopping",
    date: "1/17/21",
    id: 7,
    transaction: "PAYPAL *UPPERCUTDEL",
  },
  {
    amount: 14.29,
    category: "Restaurants",
    date: "1/17/21",
    id: 8,
    transaction: "UBER   EATS",
  },
  {
    amount: 55.63,
    category: "Gadgets",
    date: "1/17/21",
    id: 9,
    transaction: "AMZN Mktp US*671QL1OU3",
  },
  {
    amount: 120,
    category: "Utilities",
    date: "1/17/21",
    id: 10,
    transaction: "COMCAST CALIFORNIA",
  },
  {
    amount: 64.99,
    category: "Entertainment",
    date: "1/17/21",
    id: 11,
    transaction: "PAYPAL *HULU",
  },
  {
    amount: 329.55,
    category: "Gifts",
    date: "1/17/21",
    id: 12,
    transaction: "AMZN Mktp US*4E4HE9O33",
  },
  {
    amount: 74.05,
    category: "Restaurants",
    date: "1/15/21",
    id: 13,
    transaction: "UBER   EATS",
  },
  {
    amount: 8.65,
    category: "Groceries",
    date: "1/15/21",
    id: 14,
    transaction: "Amazon.com*931I47CI3",
  },
  {
    amount: 0,
    category: "N/A",
    date: "1/15/21",
    id: 15,
    transaction: "TRAVEL CREDIT",
  },
  {
    amount: 119.97,
    category: "Shopping",
    date: "1/15/21",
    id: 16,
    transaction: "PAYPAL *BOKKSU INC",
  },
  {
    amount: 13.65,
    category: "Gadgets",
    date: "1/14/21",
    id: 17,
    transaction: "Amazon.com*K66GJ0RK3",
  },
  {
    amount: 41.52,
    category: "House",
    date: "1/14/21",
    id: 18,
    transaction: "Amazon.com*HO8J681K3",
  },
  {
    amount: 13.08,
    category: "Groceries",
    date: "1/14/21",
    id: 19,
    transaction: "Amazon.com*N12924RH3",
  },
  {
    amount: 9.99,
    category: "Utilities",
    date: "1/13/21",
    id: 20,
    transaction: "APPLE.COM/BILL",
  },
  {
    amount: 0,
    category: "N/A",
    date: "1/13/21",
    id: 21,
    transaction: "APPLE.COM/US",
  },
  {
    amount: 363.84,
    category: "Restaurants",
    date: "1/13/21",
    id: 22,
    transaction: "TOCK ATMANRESA",
  },
  {
    amount: 15.27,
    category: "Gadgets",
    date: "1/12/21",
    id: 23,
    transaction: "Amazon.com*R77AT48Z3",
  },
  {
    amount: 152.51,
    category: "Gifts",
    date: "1/12/21",
    id: 24,
    transaction: "PAYPAL *S AND S",
  },
  {
    amount: 0,
    category: "N/A",
    date: "1/11/21",
    id: 25,
    transaction: "Payment Thank You-Mobile",
  },
  {
    amount: 49,
    category: "Gadgets",
    date: "1/11/21",
    id: 26,
    transaction: "SOMA SMART HOME",
  },
  {
    amount: 117.12,
    category: "Shopping",
    date: "1/10/21",
    id: 27,
    transaction: "PAYPAL *S AND S",
  },
  {
    amount: 51.37,
    category: "Drinks",
    date: "1/10/21",
    id: 28,
    transaction: "AMZN Mktp US*SY5J27633",
  },
  {
    amount: 19.99,
    category: "Coffee",
    date: "1/10/21",
    id: 29,
    transaction: "AMZN Mktp US*9F2C292G3",
  },
  {
    amount: 1.99,
    category: "Utilities",
    date: "1/10/21",
    id: 30,
    transaction: "GOOGLE *Google Storage",
  },
  {
    amount: 0,
    category: "N/A",
    date: "1/10/21",
    id: 31,
    transaction: "TRAVEL CREDIT",
  },
  {
    amount: 59.99,
    category: "Groceries",
    date: "1/10/21",
    id: 32,
    transaction: "LITTLESPOON.COM",
  },
  {
    amount: 237.06,
    category: "Gadgets",
    date: "1/10/21",
    id: 33,
    transaction: "Amazon.com*BJ24I5QO3",
  },
  {
    amount: 131.09,
    category: "Gadgets",
    date: "1/10/21",
    id: 34,
    transaction: "AMZN Mktp US*ST3CO8X93",
  },
  {
    amount: 345.94,
    category: "Insurance",
    date: "1/10/21",
    id: 35,
    transaction: "STATE FARM  INSURANCE",
  },
  {
    amount: 45.82,
    category: "Gadgets",
    date: "1/8/21",
    id: 36,
    transaction: "Amazon.com*6L0AA3ND3",
  },
  {
    amount: 37.13,
    category: "Health",
    date: "1/7/21",
    id: 37,
    transaction: "AMZN Mktp US*7Y5OY3HA3",
  },
  {
    amount: 21.74,
    category: "Groceries",
    date: "1/7/21",
    id: 38,
    transaction: "Amazon.com*IP2DY65B3",
  },
  {
    amount: 38.23,
    category: "Family",
    date: "1/6/21",
    id: 39,
    transaction: "Amazon.com*JR48P6MX3",
  },
  {
    amount: 102.71,
    category: "Restaurants",
    date: "1/5/21",
    id: 40,
    transaction: "UBER   EATS",
  },
  {
    amount: 95.71,
    category: "Utilities",
    date: "1/5/21",
    id: 41,
    transaction: "VZWRLSS*APOCC VISW",
  },
  {
    amount: 0,
    category: "N/A",
    date: "1/4/21",
    id: 42,
    transaction: "SP * NUGGETCOMFORT.COM",
  },
  {
    amount: 26.21,
    category: "Groceries",
    date: "1/4/21",
    id: 43,
    transaction: "WWW COSTCO COM",
  },
  {
    amount: 117.75,
    category: "Family",
    date: "1/4/21",
    id: 44,
    transaction: "Amazon.com*DO1ZC3EQ3",
  },
  {
    amount: 0,
    category: "N/A",
    date: "1/3/21",
    id: 45,
    transaction: "DOORDASH CREDIT",
  },
  {
    amount: 39.12,
    category: "Restaurants",
    date: "1/3/21",
    id: 46,
    transaction: "DOORDASH*TISANE",
  },
  {
    amount: 50,
    category: "Gadgets",
    date: "1/3/21",
    id: 47,
    transaction: "PAYPAL *NAMECHEAP",
  },
  {
    amount: 2.99,
    category: "Utilities",
    date: "1/3/21",
    id: 48,
    transaction: "PAYPAL *TILE INC",
  },
  {
    amount: 0,
    category: "N/A",
    date: "1/3/21",
    id: 49,
    transaction: "Peloton Membership Credit",
  },
  {
    amount: 39,
    category: "Health",
    date: "1/3/21",
    id: 50,
    transaction: "PELOTON* MEMBERSHIP",
  },
  {
    amount: 363.97,
    category: "Gadgets",
    date: "1/1/21",
    id: 51,
    transaction: "PAYPAL *CRATEANDBAR",
  },
  {
    amount: 54.66,
    category: "Restaurants",
    date: "1/1/21",
    id: 52,
    transaction: "DOORDASH*DANBI KOREAN",
  },
  {
    amount: 15.27,
    category: "Gadgets",
    date: "12/31/20",
    id: 53,
    transaction: "Amazon.com*QM79J7NE3",
  },
  {
    amount: 267.27,
    category: "Gifts",
    date: "12/31/20",
    id: 54,
    transaction: "SP * LUNYA SLEEPWEAR",
  },
  {
    amount: 43.68,
    category: "Gadgets",
    date: "12/31/20",
    id: 55,
    transaction: "Amazon.com*884RU4MO3",
  },
  {
    amount: 39.03,
    category: "Restaurants",
    date: "12/28/20",
    id: 56,
    transaction: "UBER   EATS",
  },
  {
    amount: 9.99,
    category: "Utilities",
    date: "12/28/20",
    id: 57,
    transaction: "APPLE.COM/BILL",
  },
  {
    amount: 100,
    category: "Gifts",
    date: "12/27/20",
    id: 58,
    transaction: "CS NordstromGiftCard",
  },
  {
    amount: 119,
    category: "Gadgets",
    date: "12/27/20",
    id: 59,
    transaction: "SOMA SMART HOME",
  },
  {
    amount: 25.3,
    category: "Gifts",
    date: "12/25/20",
    id: 60,
    transaction: "PAYPAL *USPS STORE",
  },
  {
    amount: 5.99,
    category: "Utilities",
    date: "12/25/20",
    id: 61,
    transaction: "APPLE.COM/BILL",
  },
  {
    amount: 194.24,
    category: "Gifts",
    date: "12/25/20",
    id: 62,
    transaction: "PAYPAL *MINTED LLC MINTED",
  },
  {
    amount: 0,
    category: "N/A",
    date: "12/25/20",
    id: 63,
    transaction: "TRAVEL CREDIT",
  },
  {
    amount: 154.78,
    category: "Groceries",
    date: "12/25/20",
    id: 64,
    transaction: "INSTACART",
  },
  {
    amount: 18,
    category: "Gadgets",
    date: "12/25/20",
    id: 65,
    transaction: "Amazon.com*546K45JR3",
  },
  {
    amount: 0,
    category: "N/A",
    date: "12/25/20",
    id: 66,
    transaction: "APPLE.COM/US",
  },
  {
    amount: 51.81,
    category: "Shopping",
    date: "12/24/20",
    id: 67,
    transaction: "PAYPAL *BUYBUYBABY",
  },
  {
    amount: 18.56,
    category: "Gadgets",
    date: "12/24/20",
    id: 68,
    transaction: "AMZN Mktp US*HK2F70403",
  },
  {
    amount: 12.01,
    category: "Groceries",
    date: "12/24/20",
    id: 69,
    transaction: "Amazon.com*CP8WV61L3",
  },
  {
    amount: 0.99,
    category: "Utilities",
    date: "12/24/20",
    id: 70,
    transaction: "PP*APPLE.COM/BILL",
  },
  {
    amount: 63.66,
    category: "Restaurants",
    date: "12/24/20",
    id: 71,
    transaction: "UBER   EATS",
  },
  {
    amount: 52.4,
    category: "Utilities",
    date: "12/23/20",
    id: 72,
    transaction: "XFINITY MOBILE",
  },
  {
    amount: 674.13,
    category: "Utilities",
    date: "12/23/20",
    id: 73,
    transaction: "PG&amp;E WEBRECURRING",
  },
  {
    amount: 60.4,
    category: "Restaurants",
    date: "12/22/20",
    id: 74,
    transaction: "TOCK ATMANRESA",
  },
  {
    amount: 45.66,
    category: "Restaurants",
    date: "12/22/20",
    id: 75,
    transaction: "UBER   EATS",
  },
  {
    amount: 2.99,
    category: "Utilities",
    date: "12/22/20",
    id: 76,
    transaction: "APPLE.COM/BILL",
  },
  {
    amount: 3,
    category: "Security",
    date: "12/21/20",
    id: 77,
    transaction: "RING MONTHLY",
  },
];

export const mockedExpenses: MockedResponse<FetchExpensesQuery> = {
  request: {
    query: FetchExpensesDocument,
    variables: {
      month: "Dry January",
    },
  },
  result: {
    data: {
      statement: {
        month: "Dry January",
        expenses,
      },
    },
  },
};
